### DISCUSSION TITLE
Execute multiples commands in one task

### DISCUSSION THREAD

**Discussion by robsonpeixoto** [batect/batect#1067] [Q&A]
I'd need to run some commands to download all dependencies of my project:
- install hex: `mix local.hex --force`
- install rebar: `mix local.rebar --force`
- auth in private repository: `mix hex.repo add oban https://getoban.pro/repo --fetch-public-key ${OBAN_KEY_FINGERPRINT} --auth-key ${OBAN_LICENSE_KEY}`
- ... more 6/7 commands just to download all dependencies

Are there a way to do it without the necessary to create a shell script?

**Comment by charleskorn** [comment]
Hey @robsonpeixoto, thanks for the question. The only alternative to creating a shell script would be combining the commands into a single command, something like `sh -c "mix local.hex --force && mix local.rebar --force && ..."`.

**Comment by robsonpeixoto** [comment]
What do think about create a `commands` feature on `Tasks` that will by default force the `entrypoint` to be `/bin/sh -c` and will join all commands in a file or using `&&` to execute?

Or just execute the commands in sequence on the same container.

```yaml
containers:
  build-env:
    image: node:14.3.0

tasks:
  hello-world:
    description: Say hello to everyone
    run:
      container: build-env
      commands:
       - echo "step1!"
       - echo "step2!"
```
