### DISCUSSION TITLE
batect for java (maven as package management)

### DISCUSSION THREAD

**Discussion by fdslk** [batect/batect#1105] [Q&A] [answered]
Batect seems like not support java in maven. Only using Gradle?

**Comment by charleskorn** [comment, marked as answer]
Hi @Fdslk, I don't quite understand your question sorry. Could you explain what you're trying to do or perhaps create a sample repo that shows the issue?

**Reply by fdslk** [reply]
Hi @charleskorn , I want to write a demo in java with checkstyle for lint. What's more, batect is used to initialize the java related env. 
```
containers:
  build-env:
    image: openjdk:13.0.2-jdk
    volumes:
      - local: .
        container: /code
      - type: cache
        name: gradle-cache
        container: /root/.gradle
    working_directory: /code
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
```
the below code is your listing sample, but I cannot find a sample for maven.
