### DISCUSSION TITLE
buildkit ssh support

### DISCUSSION THREAD

**Discussion by hpcsc** [batect/batect#1128] [Q&A] [answered]
Hi, I can see that batect supports buildkit as mentioned [here](https://batect.dev/docs/how-to/performance/#use-buildkit)

However, in order to use buildkit features, such as [ssh mount type](https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds), we need to pass additional flag `--ssh` to `docker build`. I'm not very clear how to do that when running batect command. Is it supported?

Thanks

**Comment by charleskorn** [comment]
Hi @hpcsc, unfortunately this isn't currently supported. I am actively working on replacing the Docker client used by Batect so that I can add support for features like this more easily, but I can't make any promises about when it will be available just yet.

**Reply by hpcsc** [reply]
ah ok too bad. Thanks for your answer

**Comment by mpdude** [comment]
I might be missing something, but what about adding

```yaml
    volumes:
      - local: $SSH_AUTH_SOCK
        container: /tmp/ssh_auth_sock
    environment:
      SSH_AUTH_SOCK: /tmp/ssh_auth_sock
```

... to your container definition in `batect.yml`? That should bind-mount your current SSH agent auth socket into the running container so that you can use loaded SSH identities e. g. for `git clone`.
