### DISCUSSION TITLE
Run dependencies and exit

### DISCUSSION THREAD

**Discussion by hpcsc** [batect/batect#1135] [Q&A]
Problem:
- I'm working on a Go application, using Goland
- I'm trying to run a batect task to setup dependencies (database, mock api server etc) before running integration tests (as Goland run configuration, to take advantage of Goland test output window, debugging capability etc, so the tests are run directly on host machine, not through batect). I have a batect task like:
```
setup-dependencies:
  dependencies:
  - database
  - api-mock
  run:
    container: go
    entrypoint: echo starting            # a dummy entrypoint that does nothing and exit immediately
```
- I was hoping if I run it with `--no-cleanup`, it will run dependency containers, run the entrypoint and exit without cleaning up dependencies. But it's not exiting and just waits there to be cancelled.
- My setup is probably a bit unusual but the behavior of `--no-cleanup` surprised me. I would expect if the entrypoint finishes, batect should exit and leave the containers there. Is this expected behavior?
