### DISCUSSION TITLE
docker containers labels support

### DISCUSSION THREAD

**Discussion by pmioulet** [batect/batect#1152] [Ideas]
Hi, I was just wondering if there is any plan to support the addition of labels to the containers. Some projects such as [traefik](https://github.com/traefik/traefik) allow dynamic configuration through the exploration of labels applied to containers.
Thanks for your work on this great tool !

**Comment by charleskorn** [comment]
Thanks for the suggestion @pmioulet. Do you have a link to an example of this? I've not used traefik before so I'm not familiar with this.

**Comment by pmioulet** [comment]
Below is simple example of what I would do with docker compose to use trafik as a reverse proxy in front of keycloak (please note that example is not functional as postgres is missing).

labels usage is at the bottom, ```"traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"```. These labels allow traffik to know it should route anything coming on keycloak.localhost to the keycloak container.

```
  traefik:
    container_name: traefik
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak:15.0.2
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources/keycloak/truck-load-realm-local.json:/truck-load-realm.json
    environment:
      KEYCLOAK_IMPORT: /my-realm.json
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: http://keycloak.localhost/auth
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      -  postgres
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
```
