### DISCUSSION TITLE
It feels like a batect-native "push image" task is a missing piece

### DISCUSSION THREAD

**Discussion by nth-commit** [batect/batect#1198] [Q&A]
Hey, first up, love the project - it's already simplified my workflow a lot.

Secondly, I've seen the java sample for building and pushing images, and it doesn't quite feel right to me.

[This has some implicit duplication with...](https://github.com/batect/batect-sample-java/blob/76035c1253b39ee080b27fcedc54f4753baea0ac/.batect/buildAndPushImage.sh#L8)

[This.](https://github.com/batect/batect-sample-java/blob/76035c1253b39ee080b27fcedc54f4753baea0ac/batect.yml#L15)

It's subtle, but it becomes more obvious when there's more config needed to build the image (like passing environment variables/build args around).

If we have a container definition already in batect.yml, does it make sense for there to be able to push (some related representation of it) to a docker repository? I'm a bit of a newb to this project, so feel free to tell me I'm lost.

**Comment by nth-commit** [comment]
Another options might be to optionally "lift" some configuration out of the container definition and into an image definition.

You wouldn't have to use the image definition, a container definition in batect.yml could continue to work as is, or it could alternative reference an image.

For example, this config could still work:

```yml
containers:
  roomba:
    build_directory: .
    dockerfile: ./workers/roomba/Dockerfile
    dependencies:
      - db

tasks:
  build:
    run:
      container: node-build-env
      command: yarn build

  run:
    run:
      container: roomba
    prerequisites:
      - build

  push:
    run:
      container: docker-push-env
      command: ./.batect/buildAndPushImage.sh
      environment:
        DOCKER_USER: $DOCKER_USER
        DOCKER_PASSWORD: $DOCKER_PASSWORD
    prerequisites:
      - build
      - test
```

But alternatively, something like this might be nice:

```yml
images: # New schema element
  roomba:
    build_directory: .
    dockerfile: ./workers/roomba/Dockerfile

containers:
  roomba:
    image: roomba # Might need to disambiguate from a normal image reference
    local_image: roomba # Alternatively
    dependencies:
      - db

tasks:
  build:
    run:
      container: node-build-env
      command: yarn build

  run:
    run:
      container: roomba
    prerequisites:
      - build

  push:
    push: # New schema element, `run` or `prerequisites` gets a third (exclusive) option, `image`
    image: roomba # Same disambiguation might be necessary, e.g. "local_image"
    registry: ghcr.io
    user: $DOCKER_USER
    password: $DOCKER_PASSWORD
    # etc...
```
