### DISCUSSION TITLE
exposing gradle report on failing integration/unit tests.

### DISCUSSION THREAD

**Discussion by XI1998-swapnilmarathe** [batect/batect#1220] [Q&A] [answered]
Hello,
I am trying to expose the gradle reports that are generated inside container post failure of integration/unit tests.

For now I tried with volumes option but was unsuccessful.

Here I want to write reports from container to my local directory. Any help appreciated.

These reports are html reports, so want to see them in my local host computer.

I have tried doing following but it did not work.

```
  international-transfers-service:
    image: com.demo/demo-mysql:latest
    dependencies:
      - database
    volumes:
      - local: .batect/reports
        container: /code/build/reports/tests/
        options: default
```
I tried all mount options.
From what I understand batect destroys container as well as volume in this case so reports are not written at all.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/74582859/161292189-a70cfaa7-aab3-43a2-9032-f5f79d1d058b.png">

**Comment by charleskorn** [comment]
The configuration for the volume mount you have there looks correct, assuming that is the right path that Gradle writes the test report to. 

One thing to check: is that container the one running Gradle? It looks like it's running MySQL based on the image name. If there's another container in your setup that's running Gradle, it's the one that will need the directory mount.

**Comment by XI1998-swapnilmarathe** [comment]
You are absolutely right @charleskorn. Wrong container, rookie mistake.

However, I tried with the java bundle container and it did not work


<img width="1604" alt="image" src="https://user-images.githubusercontent.com/74582859/161490024-acfe65a4-d483-433d-bfa7-a446b4de2a9b.png">

PFA
https://github.com/XI1998-swapnilmarathe/java-bundle/blob/main/batect-bundle.yml

Other question is:
1. Do we have a documentation of what variables batect provides us eg: ` <{batect.project_directory}`
2. I think first volume mentioned is overriding the volume config at bottom.
3. Can I just use batect-bundle yaml file directly inside project without creating git repo? I tried with file option in include, it but it did not work

**Reply by swapy** [reply]
Repository for ref: https://github.com/swapy/spring-boot-demo/tree/main/complete

**Reply by charleskorn** [reply]
To debug that error in your tests, it would be useful to have the exception message - you may need to turn this on with [`exceptionFormat`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLogging.html#org.gradle.api.tasks.testing.logging.TestLogging:exceptionFormat) set to `FULL`.

> 1. Do we have a documentation of what variables batect provides us eg: <{batect.project_directory}

Yep: https://batect.dev/docs/reference/config/config-variables/#built-in-config-variables

> 2. I think first volume mentioned is overriding the volume config at bottom.

They will stack - so `/code` will have everything from your project directory, and then `/code/build` will be mapped to `./.batect/reports`. They won't override each other, with the exception of the `build` directory. 

> 3. Can I just use batect-bundle yaml file directly inside project without creating git repo? I tried with file option in include, it but it did not work

That should work - could you share what you tried and what happened (eg. the error message)?

**Comment by XI1998-swapnilmarathe** [comment, marked as answer]
Hello @charleskorn,

Actually reports for errors and exceptions can be for various tests eg: integration, ut, e2e, contract and so on. So checking in console logs at docker level was cumbersome.

But you are right, I fixed by editing batect bundle for java

```
containers:
  java-build-env:
    image: azul/zulu-openjdk-alpine:17.0.0
    volumes:
      - local: <{batect.project_directory}
        container: /code
        options: cached
      - type: cache
        name: gradle-cache
        container: /home/container-user/.gradle
      - local: <{batect.project_directory}/.batect/reports
        container: /code/build/reports/tests
        options: default
    working_directory: /code
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```


I also think that it would be good to have reports volume in java-bundle.
