### DISCUSSION TITLE
Open browser after spinning up containers?

### DISCUSSION THREAD

**Discussion by adameichelkraut** [batect/batect#1222] [Ideas]
Hey! I've been using Batect now for a bit, but I've been wondering about this one: is there a way to have batect know that we are spinning up a web interface that we would want to open a browser to? For example, usually when you do a `create-react-app` and then do `npm start`, NPM would open the browser for you once the development server has started.

However, I started to wonder if it was appropriate for Batect to handle. To me, it seems like a nice efficiency to have in my `batect.yml`, but I could understand it being interesting to justify a "who should be the one to do that".

Personally, I've been trying to get to a cool spot with using batect to manage architecture diagrams using drawio's docker images (https://hub.docker.com/r/jgraph/drawio/). It would be awesome if I could have my architecture diagram automatically spin up with a `./batect diagrams` and then it automatically open the browser to the location I'd like it to open.

Interested to hear folks' thoughts!

**Comment by adameichelkraut** [comment]
also, if it makes sense I could give this one a crack at contributing :)

**Comment by charleskorn** [comment]
It's an interesting idea, and I think could be implemented through something like what #78 proposes - what do you think?

**Comment by adameichelkraut** [comment]
That sounds great! Here's a thought:

what if we specified tasks like this:

```
tasks:
    diagrams:
      post-requisites:
          - openBrowser
      run:
          container: drawio
    
    openBrowser:
        run:
            container: host
            # or
            executeOnHost: true
            command: xdg-open https://localhost:3000/
```

**Reply by adameichelkraut** [reply]
Actually wait, no because the containers above would be long lived, hypothetically so in my instance I would only need the host task to run in the prerequisites 

```
tasks:
    diagrams:
      prerequisites:
          - openBrowser
      run:
          container: drawio
    
    openBrowser:
        run:
            container: host
            # or
            executeOnHost: true
            command: xdg-open https://localhost:3000/
```
