### DISCUSSION TITLE
how can I use the option --tmpfs for running a container?

### DISCUSSION THREAD

**Discussion by sergiolpf** [batect/batect#1241] [Q&A] [answered]
Hi, I am new to Batect and I am kind of lost....

I have an image built with tmpfs and when I try to run the image with batect I get the following 
`df: /opt/datafiles: No such file or directory
Expected tmpfs to be mounted at /opt/datafiles`

This is my batect.yml
```
containers:
  myImageWithTmpfs:
    image: urlToMyImage
    ports:
      - local: 1444
        container: 1443
tasks:
  runImage:
    run:
      container: myImageWithTmpfs
```

so how can I add the `--tmpfs '/opt/datafiles'` to run?
