### DISCUSSION TITLE
namespaced includes

### DISCUSSION THREAD

**Discussion by hpcsc** [batect/batect#1351] [General]
Is namespaced include like [Taskfile](https://taskfile.dev/usage/#including-other-taskfiles) something you will consider to support in batect?

it's useful in multi-components repository, e.g a repository like below where I have one batect file for each component

```
batect.yml
components
  a
    batect.yml
  b
    batect.yml
```

root `batect.yml`:

```yaml
include:
  a: ./components/a/batect.yml
  b: ./components/b/batect.yml
```

with this, it automatically includes all child containers and tasks in corresponding namespaces

Tasks can be invoked like `./batect a:task-from-component-a` or `./batect b:task-from-component-b`
