### DISCUSSION TITLE
How to dynamically switch included config files?

### DISCUSSION THREAD

**Discussion by gabrielsadakatw** [batect/batect#1370] [Q&A] [answered]
Is there a way to use a config variable to define which config file to include per run? 

For example:

```
config_variables:
  target-db-config-file:
    description: Batect config file for target db
    default: examples/db/batect-target-db.yml
include:
  - <{target-db-config-file}
```

That way when executing a task we can pass in the path to the file to be included e.g. `./batect --config-var target-db-config-file=examples/db/batect-target-db.yml run`.

Trying that resulted in the following error:

```
(at include[0] on line 23, column 5): Included file '<{source-db-config-file}' (resolved to .../...{source-db-config-file}') does not exist.
```
