### DISCUSSION TITLE
config variable of type int

### DISCUSSION THREAD

**Discussion by steve-james-xero** [batect/batect#1446] [Q&A] [answered]
I am trying to create a container with a port taken from a config value. I thought I could do something like this:

```
config_variables:
  container_port:
    description: port db is available on in the docker network
    default: 5432

db:
    build_directory: .
    dockerfile: dockerfile.db
    ports:
      - local: 5400
        container: <container_port
```

The schema validation complains that the default property on the config variable is of type string. I've tried various workarounds of such as `default: "5432"` but it still doesn't work. 

Is this achievable and if so how?

Thanks.
