### DISCUSSION TITLE
Error when configuring batect cache on GitHub Actions

### DISCUSSION THREAD

**Discussion by davidtan-tw** [batect/batect#1448] [Q&A]
Hi there,

As always - thanks for the great work on this awesome tool.

I'm trying to persist batect caches between builds on CI (GitHub Actions), and batect has [clear documentation](https://batect.dev/docs/using-batect-with/ci/github-actions/) on that.

However, after following the documentation and updating my CI pipeline (changes [here](https://github.com/davidtan-tw/credit-score-prediction/blob/main/.github/workflows/ci.yaml#L6-L14)), the job fails with the error: `error validating build context: no permission to read from '/home/runner/work/credit-score-prediction/credit-score-prediction/.batect/caches/poetry-cache-and-artifacts/artifacts/.../parso-0.8.3-py2.py3-none-any.whl'` (see [build failure](https://github.com/davidtan-tw/credit-score-prediction/actions/runs/4023872953/jobs/6915247771)). I've triggered the build twice and the error was the same.

In my batect.yml, I specify two caches (see code sample below), and this error is related to the second cache. When I comment out the second cache, the error goes away. So **my question is**: how come it's possible to persist the first cache, but not the second?

```
containers:
  dev:
    build_directory: .
    volumes:
      - local: .
        container: /code
      - type: cache   
        name: python-dev-dependencies
        container: /code/.venv                            # project dependencies
      - type: cache 
        name: poetry-cache-and-artifacts
        container: /root/.cache/pypoetry           # poetry downloads dependencies to this folder. Caching this helps to speed up build/installation by avoiding the need to download large dependencies again. 
```

Cheers, and thanks!
