### DISCUSSION TITLE
Show dependencies logs for a task

### DISCUSSION THREAD

**Discussion by hqtoan94** [batect/batect#1470] [Q&A] [answered]
I'm using `batect` to run my execute e2e test for my application. But it's currently failed because one of the dependencies got some error. My question is that, is there any option we can show logs of all dependencies to the system logs for troubleshooting purpose?

For example, my yml:
```
containers:
    server-app:
        ...

    frontend-app:
        ...
        dependencies:
            - server-app

    automation-app:
        ...
        dependencies:
            - frontend-app
```

When starting dependencies of `automation-app`, there is no logs for me to know that why the dependencies is not working.
(Actually I can create new tasks and check for each dependencies but that would be better if we have an option to see the error in the first place).
