### DISCUSSION TITLE
Run build with current user

### DISCUSSION THREAD

**Discussion by dnguyenzd** [batect/batect#1500] [Q&A] [answered]
I have a golang container defined as follow:

```yaml
containers:
  build-env:
    build_directory: ./.batect/golang-build-env
    volumes:
      - local: .
        container: /app
        options: cached
      - type: cache
        name: go-cache
        container: /go
    working_directory: /app
    environment:
      GOCACHE: /go/cache
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```

`./.batect/golang-build-env/Dockerfile`
```
FROM golang:1.19.1
WORKDIR /app

RUN go install gotest.tools/gotestsum@v1.10.0
```

When I run a task in this container that requires Go to get external dependencies, it got following error:

```
go: downloading github.com/rs/zerolog v1.29.0
go: writing go.mod cache: open /go/pkg/mod/cache/download/github.com/mattn/go-colorable/@v/v0.1.13.mod298498081.tmp: permission denied
go: writing go.mod cache: open /go/pkg/mod/cache/download/github.com/mattn/go-isatty/@v/v0.0.18.mod427131847.tmp: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/rs: permission denied
go: writing go.mod cache: open /go/pkg/mod/cache/download/golang.org/x/sys/@v/v0.7.0.mod939984059.tmp: permission denied
go: writing go.mod cache: open /go/pkg/mod/cache/download/golang.org/x/sys/@v/v0.6.0.mod911902081.tmp: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/coreos: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/pkg: permission denied
go: writing go.mod cache: open /go/pkg/mod/cache/download/github.com/mattn/go-isatty/@v/v0.0.16.mod474941318.tmp: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/rs: permission denied
go: writing go.mod cache: open /go/pkg/mod/cache/download/golang.org/x/sys/@v/v0.0.0-20220811171246-fbc7d0a398ab.mod140954425.tmp: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/github.com/godbus: permission denied
cmd/main.go:4:2: mkdir /go/pkg/mod/cache/download/github.com/rs: permission denied
```

As I can see, this error is because:
- `go install gotestsum` in Dockerfile causes `/go/pkg` to be owned by root
- when running a task, Go runs as current user and therefore doesn't have permission to `/go/pkg` to download dependencies

What's your recommendation in this case? Ideally I would like to have access to current user uid/gid during build process so that I can do `chown` after installing `gotestsum`. 

Minimum repo to reproduce the issue: https://github.com/dnguyenzd/go-batect-permission
