### DISCUSSION TITLE
Unable to pass an environment variable to the Dockerfile build process

### DISCUSSION THREAD

**Discussion by gavinharriss** [batect/batect#1529] [Q&A] [answered]
I'm struggling with an issue where I need to pass an environment variable into the `Dockerfile` build process. Can anyone point out what I'd doing wrong?

I've created a minimal example to quickly reproduce the issue at https://github.com/gavinharriss/batect-dockerfile-env-issue

One workaround I attempted was to use `build_args` instead of `environment` settings, but this also failed.

Any pointers would be greatly appreciated. Thank you in advance as I've been banging my head against this for a few days now.

**Comment by charleskorn** [comment, marked as answer]
If you'd like to pass an environment variable to the `Dockerfile` build process, there are a couple of things you need to do:

1. Pass the environment variable as a build arg to the Dockerfile in your Batect config, for example:

    ```yaml
    containers:
      aspnet:
        build_directory: . 
        build_args:
           secret_key: $secret_key # Note that the <{...} syntax is for config variables, not environment variables
    ```

2. Declare the build arg in your Dockerfile with `ARG` and then either create an environment variable with the value of the build arg, or use the value directly in subsequent commands:

    ```Dockerfile
    ARG secret_key
    ENV secret_key=$secret_key # or eg. RUN do-secret-stuff --key=$secret_key
    ```

There's more detailed information about build args in the Docker documentation: https://docs.docker.com/engine/reference/builder/#arg
