### DISCUSSION TITLE
Pushing built and tested images

### DISCUSSION THREAD

**Discussion by or1can** [batect/batect#803] [Q&A] [answered]
We're using batect in a few projects successfully, but have one recurring issue that would be nice to solve in a clean way and that's pushing built and tested images.

We follow a fairly simple pattern most of the time project container and one or more test containers, e.g.

```
containers:
  project:
    build_directory: project_container/
    ...
  test-runner:
    build_directory: test_runner_container/
    ...
tasks:
  test:
    run:
      container: test-runner
    dependencies:
      - project
```

This works great, `batect` builds our project and test runner images, launches the containers and runs tests as expected in a nice isolated way with all the benefits of batect.

When it comes to pushing images, it's a little dirtier. We could easy add a `push` or `release` task to push an image, but we want to reference the container that was built and tested by batect.

The sample Java project has an [example of this](https://github.com/batect/batect-sample-java/blob/main/.batect/buildAndPushImage.sh), but it executes a fresh build, essentially outside batect and uses a `latest` tag.

We could run `batect --output=all` option to see logs from all containers in the task and filter out the "Image build | Successfully built" line for the project container in our CI, then tag and push that if tests pass.

It would be nice, however, if there were a simple way to reference the ID of the image that batect built and ran in a task, so we could have a push task that automatically new the right image to push, e.g. some kind of expression in the batect config file.

The problem we're trying to avoid is that while our build and tests are nicely isolated, our push is not and it is possible (albeit unlikely) that jobs running at the same time on the same docker host might interfere with each other when pushing.

Is there some way to achieve this already that I've missed, or do you think it makes sense as a feature?

**Comment by charleskorn** [comment]
Hey @or1can, this is a problem that's been in the back of my mind for a while. At the moment, there's no easy way to do what you describe. However, as a temporary workaround, running `docker build` outside Batect with the same input (ie. same Dockerfile and same files that are copied into the image) and same Docker daemon should result in a build cache hit and Docker should give you the same image back. 

> it is possible (albeit unlikely) that jobs running at the same time on the same docker host might interfere with each other when pushing

Is this because both jobs might try to push the same tag? (eg. both could try to push `my-project:latest`) If so, I'd highly recommend using unique per-build tags to avoid this issue. 

All of that aside, I'd like to implement something that solves this problem, and I'd be interested in your feedback on what I'm thinking:

 I'm thinking of adding a `--tag-image` command line option, so you could do something like this to build, test and push your image:

```shell
./batect --tag-image my-project=registry.mycompany.com/my-project:v1.2.3 test # Run the 'test' task, and tag the image built for the 'my-project' container as 'registry.mycompany.com/my-project:v1.2.3'
docker push registry.mycompany.com/my-project:v1.2.3
```

An alternative / additional option would be to add a `--push` flag on top of `--tag-image` that would then push the tagged image(s), removing the need for `docker push`, but that might be a future improvement.

The main downside of this approach is that it forces you to run a task before you can build and tag an image - which is great when you want to test the image before pushing it, but might make other scenarios more difficult when you don't want to run a task at all.

**Reply by or1can** [reply]
Running `docker build` outside is the approach we've gone for at the moment - we:

1. docker build outside Batect and tag
2. use --override-image with tag from step 1 when running subsequent tasks
3. push image from step 1 after tasks and other steps complete successfully

While the `--tag-image` option would perhaps make step 1 of that process cleaner, what exactly would happen if there were multiple tasks that needed to be run sequentially, e.g.

```yaml
containers:
  project:
    build_directory: project_container/
    ...
  test-runner:
    build_directory: test_runner_container/
    ...
tasks:
  config-test:
    run:
      container: project
      command: configcheck
  test:
    run:
      container: test-runner
    dependencies:
      - project
```

when would the image be tagged when running the first task, and what would happen when the second task is run (e.g. would the image be rebuilt, would the tagged image from the first run be used?) Obviously, some of this could be handled with task prerequisites, but we like separate tasks for different stages in CI jobs, but want to ensure consistency between each task run.
