### DISCUSSION TITLE
Is it possible to use batect with Jenkins Pipeline?

### DISCUSSION THREAD

**Discussion by sandarenu** [batect/batect#870] [Q&A] [answered]
Is it possible to use batect with Jenkins Pipeline? Can someone points to a good example on it?

**Comment by charleskorn** [comment]
Hi @sandarenu, it's definitely possible, but I don't have any examples that I can share (maybe someone in the community has one). It should be possible to use Batect with the shell runner in your `Jenkinsfile`, for example:

```groovy
pipeline {
    stages {
        stage('build') {
            steps {
                sh './batect build'
            }
        }
    }
}
```

**Reply by sandarenu** [reply]
When Jenkins is running on a docker container this does not work.  I think some volume mapping required. Can you help on that?

```
+ ./batect build

Batect can collect anonymous environment, usage and performance information.

This information does not include personal or sensitive information, and is used only to help improve Batect.

More information is available at https://batect.dev/privacy, including details of what information is collected and a formal privacy policy.



It looks like Batect is running in a non-interactive session, so it can't ask for permission to collect and report this information. To suppress this message:

* To allow collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'true', or run './batect --permanently-enable-telemetry'.

* To prevent collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'false', or run './batect --permanently-disable-telemetry'.



No data will be collected for this session.



Running build...

Pulling maven:3.6.1...

Pulled maven:3.6.1.

Running mvn clean install -DskipTests in build-env...



Error: Could not run container build-env.

Starting container '02e5280bda321e75e5d1cc87b5c16de40d526d1ff52f8a51d7a8b47ced470599' failed: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/batect-group-6532447838109901493\\\" to rootfs \\\"/var/lib/docker/overlay2/2133016a0c6d1a93053346d4ddc1cabad7278bcfd1af77c831d62eb3d2c6b5a9/merged\\\" at \\\"/var/lib/docker/overlay2/2133016a0c6d1a93053346d4ddc1cabad7278bcfd1af77c831d62eb3d2c6b5a9/merged/etc/group\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type



Cleaning up...



The task build failed. See above for details.

script returned exit code 255
```

**Reply by charleskorn** [reply]
Ah - you'll need to mount `/tmp` from the host into `/tmp` inside the Docker container Jenkins is using so that Batect can access it.

**Reply by sandarenu** [reply]
@charleskorn I have mounted the `/tmp` directory to jenkins docker. Still I'm unable to get it working. 
Seems like issue with mounting the code to batect build environment.

```
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/code). Please verify you invoked Maven from the correct directory. -> [Help 1]
```

Following is my batect.yml

```
project_name: test-project

containers:
  build-env:
    image: maven:3.6.1
    volumes:
      - local: .
        container: /code
#        options: cached
#      - local: .m2
#        container: /home/container-user/.m2
#        options: cached
    working_directory: /code
#    run_as_current_user:
#      enabled: true
#      home_directory: /home/container-user


tasks:
  build:
    description: Build the application.
    run:
      container: build-env
      command: mvn clean install -DskipTests


```

**Reply by charleskorn** [reply]
Accessing the Docker daemon from within a container is tricky, particularly when it comes to file paths. The paths that Batect sees inside the container must match those that the daemon sees outside the container. I'm guessing that the path that the code is available at inside the container does not match the path the daemon can see (or the code might only exist inside the container). If you can make the absolute paths to the code exactly the same both outside the container and inside the container, then it should work.

Alternatively, you could either:

* run a second Docker daemon inside the build container that Jenkins starts - this will solve the issue of the different paths but will mean you cannot take advantage of features such as image caching as the Docker daemon's cache will be destroyed when Jenkins removes the build container
* run the build directly on the agent (ie. tell Jenkins not to start a build container)

**Comment by sandarenu** [comment, marked as answer]
Finally managed to get it working. Trick is in the volume mapping. You have to use the path at the host machine, where jenkins is keeping the checked out code. Also need to remove `run_as_current_user` section as well. 

```
containers:
  build-env:
    image: maven:3.6.1
    volumes:
      - local: /sandarenu/data/jenkins/workspace/RNM_Test
        container: /code
        options: cached
      - local: /sandarenu/data/jenkins/workspace/RNM_Test/.m2
        container: /var/jenkins_home/workspace/RNM_Test/.m2
        options: cached
    working_directory: /code
#    run_as_current_user:
#      enabled: true
#      home_directory: /home/container-user
```
