### ISSUE TITLE
Add a way to "forward" task names to the command

### ISSUE THREAD

**Issue by sschuberth** [batect/batect#1012]
### Describe the problem you'd like to solve

I'd like to avoid repetitive code as

```
tasks:
  test:
    run:
      container: build-env
      command: ./gradlew test
  funTest:
    run:
      container: build-env
      command: ./gradlew funTest
  installDist:
    run:
      container: build-env
      command: ./gradlew installDist
```

### Describe the solution you'd like

It would be nice if the task could be written as some kind of generic template that just "forwards" the task name to the command. Naively, something like

```
tasks:
  *:
    run:
      container: build-env
      command: ./gradlew $taskName
```

### Describe alternatives you've considered

Maybe this could be archived with some thing of native YAML construct, but I've not yet found out how exactly.

**Comment by charleskorn** [comment]
Hey @sschuberth, thanks for the suggestion. 

It's not quite as nice as what you've suggested, but you could achieve something similar by [passing additional arguments to the task from the command line](https://batect.dev/docs/reference/cli/#pass-additional-arguments-to-a-task).

So if your configuration file looked like this:

```yaml
tasks:
  run-gradle:
    run:
      container: build-env
      command: ./gradlew
```

You could then run `./batect run-gradle -- build` to run `./gradlew build` or `./batect run-gradle -- test` to run `./gradlew test`, for example.
