### ISSUE TITLE
Pass extra arguments to prerequisite tasks

### ISSUE THREAD

**Issue by charleskorn** [batect/batect#1053]
Is it also possible to pass those extra arguments for tasks (here: "build") as part of [task prerequisites](https://batect.dev/docs/reference/config/tasks#prerequisites)? I tried

    task:
      prerequisites:
        - run-gradle build

and

    task:
      prerequisites:
        - run-gradle -- build

but neither works.

_Originally posted by @sschuberth in https://github.com/batect/batect/issues/1012#issuecomment-934209675_

**Comment by charleskorn** [comment]
@sschuberth could you talk a little more about your use case? I'm interested to understand what you're trying to achieve in case there's another way to provide the same end result in another way.

**Comment by sschuberth** [comment]
Sure thing. I've defined a task like

```
tasks:
  gradle:
    description: >-
      A generic task that "forwards" task arguments to Gradle. Use it like
      `./batect gradle -- installDist`.
    run:
      container: build
      command: ./gradlew --stacktrace
```

and now my idea was to define another task like

```
  requirements:
    description: >-
      A task to check ORT's requirements against the runtime container.
    prerequisites:
      - gradle installDist
    run:
      container: run
      command: ./cli/build/install/ort/bin/ort requirements
```

That, however, does not work. What I'm currently doing as a work-around is to define yet one more intermediate task like

```
  buildCli:
    description: >-
      A convenience task to build (but not run) ORT's command line interface.
    run:
      container: build
      command: ./gradlew --stacktrace installDist
```

and then replace the prerequisite "gradle installDist" with "buildCli".
