### ISSUE TITLE
Unable to mount docker socket when running has current user on a Mac

### ISSUE THREAD

**Issue by or1can** [batect/batect#1435]
### Describe the bug

Until recently (probably the MacOS Ventura upgrade), I was able to follow some obscure instructions from https://github.com/docker/for-mac/issues/410 to access my host `ssh-agent` from inside a container.

I had this working in batect, using this snippet of container configuration:

```
environment:
  SSH_AUTH_SOCK: "/run/host-services/ssh-auth.sock"
volumes:
  - local: "/run/host-services/ssh-auth.sock"
    container: "/run/host-services/ssh-auth.sock"
```

but this has stopped working and now reports a read-only file system exception.

This works as expected when using `docker` CLI directly, but only works in batect if you do not enable `run_as_current_user`.

### Reproduction repo

No specific repository required.

### Steps to reproduce

With the following `batect.yml`, run `./batect shell`
```
containers:
  ubuntu:
    image: ubuntu:22.04
    command: bash
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
    environment:
      SSH_AUTH_SOCK: "/run/host-services/ssh-auth.sock"
    volumes:
      - local: "/run/host-services/ssh-auth.sock"
        container: "/run/host-services/ssh-auth.sock"
tasks:
  shell:
    run:
      container: ubuntu
```

### Expected behaviour

A shell should be started in the `ubuntu` container, with access to `ssh-agent` from the host.

### Actual behaviour

The following error is observed:

```
Running shell-tf...
ubuntu: creating container...

Error: An unexpected exception occurred during execution.
During execution of step of kind 'CreateContainerStep': java.nio.file.FileSystemException: /run: Read-only file system

Clean up: done

The task shell-tf failed. See above for details.
```

Removing the `run_as_current_user` setting will allow the task to start, but then it's not running as the current user :sad

### Version information

```plain text
Batect version:    0.83.2
Built:             2022-12-28 05:12:33 +0000
Built from commit: 5943e63de9f6fe6883f3d80c30d887557f4b18f8 (commit date: 2022-12-28 15:49:23 +1100)
JVM version:       Homebrew OpenJDK 64-Bit Server VM 18.0.2.1
OS version:        Mac OS X 13.1 x86_64
Docker version:    20.10.21 (API version: 1.41, minimum supported API version: 1.12, commit: 3056208, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.37.1 (Apple Git-137.1)

For documentation and further information on Batect, visit https://github.com/batect/batect.
```
