### ISSUE TITLE
sudo account validation failure when run_as_current_user enabled

### ISSUE THREAD

**Issue by or1can** [batect/batect#1550]
### Describe the bug

In issue #1435, we resolved an issue with being unable to mount `/run/host-services/ssh-auth.sock` and can now mount it successfully.

Unfortunately, the mounted file is owned by root and it was suggested to work around this limitation in Docker by using `sudo`. 

To avoid coding in user or group names, I'm using the following command to change ownership of the socket:

```
sudo chown --reference=/home/container-user /run/host-services/ssh-auth.sock
```

but this results in an error:

```
sudo: account validation failure, is your account locked?
sudo: a password is required
```

This appears to be because `/etc/shadow` has not been updated when `/etc/passwd` and `/etc/group` have been changed.

### Reproduction repo

No specific repository required.

### Steps to reproduce

With the following batect.yml:

```
containers:
  ubuntu:
    build_directory: .
    command: bash
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
    environment:
      SSH_AUTH_SOCK: "/run/host-services/ssh-auth.sock"
    volumes:
      - local: "/run/host-services/ssh-auth.sock"
        container: "/run/host-services/ssh-auth.sock"
tasks:
  shell:
    run:
      container: ubuntu
```

and Dockerfile:

```
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y openssh-client sudo git

RUN echo "ALL ALL=(root) NOPASSWD: /usr/bin/chown --reference=/home/container-user /run/host-services/ssh-auth.sock" >> /etc/sudoers

#RUN echo "root:*:19383:0:99999:7:::" > /etc/shadow
#RUN echo "Kevin:*:19383:0:99999:7:::" >> /etc/shadow

# Entrypoint to make SSH agent work
# sudo chown --reference=/home/container-user /run/host-services/ssh-auth.sock
```

run `./batect shell`

and in the shell try `sudo chown --reference=/home/container-user /run/host-services/ssh-auth.sock` and you'll get the described error.

adding the following (changing `container-user` to the right user name) to the Dockerfile:

```
RUN echo "root:*:19383:0:99999:7:::" > /etc/shadow
RUN echo "container-user:*:19383:0:99999:7:::" >> /etc/shadow
```

will allow the `sudo` command to succeed.

### Expected behaviour

With a properly configured `/etc/sudoers`, `sudo` will run without authentication errors.

### Actual behaviour

Running `sudo` in a container configured to `run_as_current_user`, with a correctly configured `/etc/sudoers` will result int the following error:

```
sudo: account validation failure, is your account locked?
sudo: a password is required
```

### Version information

```plain text
Batect version:    0.83.9
Built:             2023-06-17 07:21:44 +0000
Built from commit: 0de7f9c72f58dcb18f54dd25c76f440fd6038c7a (commit date: 2023-06-15 10:27:39 +0000)
JVM version:       Homebrew OpenJDK 64-Bit Server VM 19.0.2
OS version:        Mac OS X 13.4 x86_64
Docker version:    24.0.2 (API version: 1.43, minimum supported API version: 1.12, commit: 659604f, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.39.2 (Apple Git-143)

For documentation and further information on Batect, visit https://github.com/batect/batect.
```
```


### Any other information

_No response_
