### ISSUE TITLE
Can not connect to database

### ISSUE THREAD

**Issue by floratmin** [batect/batect#1602]
### Describe the bug

I was following a tutorial and could not connect to the database at first. After trying some different configurations all of a sudden it started to work. But when trying to replicate the settings in an other project it can again not connect to the database.

### Reproduction repo

[Repo](https://github.com/floratmin/batect-database)

### Steps to reproduce

`./batect install-deps && ./batect start-server`

### Expected behaviour

The connection to the database should be established and the query should be executed.

### Actual behaviour

```
Error: connect ECONNREFUSED 172.28.0.2:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.28.0.2',
  port: 5432
}
```

### Version information

```plain text
Batect version:    0.85.0
Built:             2023-09-15 01:22:00 +0000
Built from commit: 1c406375411fdb13c84f559d71acfa4686630764 (commit date: 2023-09-15 10:56:53 +1000)
JVM version:       Ubuntu OpenJDK 64-Bit Server VM 11.0.20.1
OS version:        Linux 5.15.0-86-generic amd64 (Ubuntu 22.04.3 LTS (jammy))
Docker version:    24.0.6 (API version: 1.43, minimum supported API version: 1.12, commit: 1a79695, operating system: 'linux', architecture: 'amd64', experimental: false)
Git version:       2.35.0
```

**Comment by floratmin** [comment]
I realized that this error occurs only when not specifying a volume for the database. In the tutorial this was exactly what they were doing to use the database for testing. So the database and all tables get newly created for each run. So when I add the following under `dbs` the error is not thrown.

```yaml
  dbs:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - local: ./postgres-data
        container: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: db
```
But I found it very helpful using a fresh database for each test run.
