### ISSUE TITLE
Allow env variable interpretation in volume paths

### ISSUE THREAD

**Issue by flobas** [batect/batect#289]
Hi there,

I started playing with batect (very great tool!) and I noticed host environment variables aren't taken into account when mounting volumes.

Here is my test: I want to build and run a container that writes a simple file to my host through a Docker volume.

- Batect description (v0.38.0)
```yml
containers:
  test:
    build_directory: .
    volumes:
      - local: /home/$USER/test
        container: /home/test

tasks:
  setup:
    run:
      container: test
```
- Dockerfile
```Dockerfile
FROM alpine

RUN mkdir -p /home/test

WORKDIR /home/test

CMD touch my-shared-file
```
- Trace
```bash
[gobah@labs batect-issue]$ ls /home
gobah
[gobah@labs batect-issue]$ echo $USER
gobah
[gobah@labs batect-issue]$ ./batect setup
Running setup...
test: running
setup finished with exit code 0 in 0.9s.
[gobah@labs batect-issue]$ ls /home
'$USER'   gobah
```

It would be great to allow environment variable interpretation for volume paths.

For a specific case, I want to run integration tests via batect inside GitlabCI. It works very well but I need to mount a volume from `/builds/$CI_PROJECT_PATH/` to get my output files. I can obviously read the environment variable and then dynamically "rewrite" my batect file but it would be more elegant to use the env variable directly in the volume paths.
