### ISSUE TITLE
Make cached resources available across multiple containers

### ISSUE THREAD

**Issue by DavidHe1127** [batect/batect#461]
My use case is I have 2 tasks and each one needs to run in a different container. They both need the same `node_modules` to be able to run and it has to be installed inside the container rather than on the build agent.

Currently, I am installing it twice in each task run and thinking if it is possible to share it between these 2 containers. i.e node_modules installed on container one when running the first task can share it with container two so no repeated installation is required prior to running task 2.

I have read the docs about [volume caching](https://batect.dev/tips/Performance.html) but I couldn't work out how I can learn from it to fix my problem.

Any idea?

**Comment by charleskorn** [comment]
Hi @DavidHe1127, thanks for the question! It's definitely possible to share the `node_modules` folder between containers. You have two options:

* you can mount a shared cache into both containers - all you need to do is specify the same `name` and they'll both use the same underlying volume

* you can mount a local directory into both containers 

Hope that helps!

**Comment by DavidHe1127** [comment]
@charleskorn thanks for that. I've worked out this as well.

```yml
containers:
  build-env:
    image: node:10
    volumes:
      - local: .
        container: /code
        options: cached
      - type: cache
        name: node-modules
        container: /code/node_modules
    working_directory: /code
    # environment:
    #   BUNDLE_PATH: /bundle-cache
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user

  test-env:
    image: node:alpine
    volumes:
      - type: cache
        name: node-modules
        container: /code/node_modules
    working_directory: /code
    # environment:
    #   BUNDLE_PATH: /bundle-cache
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```

This way `node_modules` is also available in `test-env` container as well.
