### ISSUE TITLE
Set environment variable on dependency for specific task

### ISSUE THREAD

**Issue by zizhongzhang** [batect/batect#551]
Hi Team,

I have an app the behaviour of which changes based on which mode it is on.
Is it possible to set 'MODE' at batect task level which then pass down to container level at container start-up? below is one hypothetical example.

```
sample-app:
    build_directory: .batect/app
    dependencies:
      - another-service
    ports:
      - local: 8080
        container: 80
```

```
journeyTest
    description: Run journey test for sample-app.
    group: Test tasks
    prerequisites:
      - build
    dependencies:
      - sample-app
    run:
      environment:
        MODE: SideBySide
      container: build-env
      command: test ...
```

**Comment by charleskorn** [comment]
Hi @zizhongzhang, thanks for the suggestion! This isn't something that's possible at the moment but I can add it to my backlog.

**Comment by charleskorn** [comment]
Hi @zizhongzhang, this is now possible with [`customise`](https://batect.dev/docs/reference/config/tasks#customise) which was introduced in 0.61.0 - sorry for not coming back to this issue earlier.

For example:

```yaml
journeyTest
  description: Run journey test for sample-app.
  group: Test tasks
  prerequisites:
    - build
  dependencies:
    - sample-app
  run:
    container: build-env
    command: test ...
  customise:
    sample-app:
      environment:
        MODE: SideBySide
```
