### ISSUE TITLE
Any way can pass arguments to a command that in prerequisites?

### ISSUE THREAD

**Issue by askfor** [batect/batect#554]
Hi, Is there any way can pass arguments to a command that in prerequisites?

**Comment by charleskorn** [comment]
Hi @askfor, thanks for the question. At the moment, that's not supported easily, but there are ways - could you perhaps share what you're trying to achieve so I can understand more?

**Comment by askfor** [comment]
For example, I want to checkout a certain branch and then run mvn install.

```
containers:
  git:
    image: alpine/git:latest
    volumes:
      - local: .
        container: /code
        options: cached
    working_directory: /code
  
  jdk:
    image: maven:3.6.3-jdk-8
    volumes:
      - local: .
        container: /code
      - local: ./.mvn/.m2/repository/
        container: /root/.m2/repository/
    working_directory: /code

tasks:
  checkout:
    run:
      container: git
      command: "'git checkout $branch'"
      entrypoint: /bin/sh -c

  install:
    run:
      container: jdk
      command: "'mvn install'"
      entrypoint: /bin/sh -c
    prerequisites:
      - checkout
   
```

**Comment by askfor** [comment]
For example, I want to checkout a certain branch and then run mvn install.

```
containers:
  git:
    image: alpine/git:latest
    volumes:
      - local: .
        container: /code
        options: cached
    working_directory: /code
  
  jdk:
    image: maven:3.6.3-jdk-8
    volumes:
      - local: .
        container: /code
      - local: ./.mvn/.m2/repository/
        container: /root/.m2/repository/
    working_directory: /code

tasks:
  checkout:
    run:
      container: git
      command: "'git checkout $branch'"
      entrypoint: /bin/sh -c

  install:
    run:
      container: jdk
      command: "'mvn install'"
      entrypoint: /bin/sh -c
    prerequisites:
      - checkout
   
```

**Comment by charleskorn** [comment]
In that particular case, it might be easiest to use an environment variable - so your config file would become something like this:

```yaml
...

tasks:
  checkout:
    run:
      container: git
      command: "'git checkout $branch'"
      entrypoint: /bin/sh -c
      environment:
        branch: $branch

...
```

Which can then be run with something like `branch=my-branch ./batect install`.

Does that work for you?
