### ISSUE TITLE
Can not mount /var/run/docker.sock in windows 

### ISSUE THREAD

**Issue by askfor** [batect/batect#555]
Hi, It seems "/var/run/docker.sock" can't be mounted in windows.
The path was resolved to "D:/var/run/docker.sock" according to the error message.
```
Output from Docker was: Mount denied:
                                     The source path "D:/var/run/docker.sock"
                                                                             doesn't exist and is not known to Docker
```
```
  compose:
    image: docker/compose:1.26.0
    privileged: true
    volumes:
      - local: .
        container: /code
      - local: /var/run/docker.sock
        container: /var/run/docker.sock
    working_directory: /code
```
