### ISSUE TITLE
GitHub action reports no telemetry, even with explicit flag

### ISSUE THREAD

**Issue by binkley** [batect/batect#632]
*NB* -- repo referenced in this issue: https://github.com/binkley/kotlin-dice.  I'm looking for advice:
1. GitHub does not do the "right thing"
2. Batect does not do the "right thing"
3. Both?

I'd like my local projects to be as clean and faithful as possible.  "Toy" projects like this are how I learn a technology at depth.

----

Following the instructions of output for telemetry, I expected warnings/complaints from Batect to go away while using GitHub actions.  I set up GitHub to cache files from Batect (or tried).

*Where is the file stored to mark telemetry*?  I'd like to cache this file in GitHub actions.  I did try 2 times in a row, in case there was a file created the first time, and available for caching the second.

Following the instructions on the output of my GitHub action when using Batect, I expected the extra output to go away:
```
Run ./batect --permanently-enable-telemetry run
Downloading batect version 0.58.2 from https://dl.bintray.com/batect/batect/0.58.2/bin/batect-0.58.2.jar...
#=#=#                                                                         
##O#- #                                                                       
##O=#  #                                                                      

                                                                           0.1%
########################################                                  56.8%
######################################################################## 100.0%
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
batect can collect anonymous environment, usage and performance information.
This information does not include personal or sensitive information, and is used only to help improve batect.
More information is available at https://batect.dev/Privacy.html, including details of what information is collected and a formal privacy policy.

It looks like batect is running in a non-interactive session, so it can't ask for permission to collect and report this information. To suppress this message:
* To allow collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'true', or run './batect --permanently-enable-telemetry'.
* To prevent collection of data, set the BATECT_ENABLE_TELEMETRY environment variable to 'false', or run './batect --permanently-disable-telemetry'.

No data will be collected for this session.

Telemetry successfully enabled.
```
Here is my step in GitHub actions to run Batect:
```
      - name: Validate batect
        run: ./batect --permanently-enable-telemetry run
```
Here is my cache for GitHub actions:
```
      - name: Restore cached Batect local
        id: batect-cache
        uses: actions/cache@master
        env:
          cache-name: cache-batect
        with:
          path: ~/.batect
          key: ${{ runner.os }}-batect-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-batect-${{ env.cache-name }}
            ${{ runner.os }}-batect-
            ${{ runner.os }}-
```
