### ISSUE TITLE
Passthrough of current working directory folder name to local volume mount path

### ISSUE THREAD

**Issue by doug-ferris** [batect/batect#636]
Sorry. I had 0 idea how to title this in a way that makes sense.

My current use case is that I have a project that deploys to AWS Lambda and uses Amazon CDK to build the Cloudformation that will be deployed.

I currently have the following batect config:
```yaml
containers:
  build-env:
    dockerfile: build/Dockerfile
    build_directory: .
    volumes:
      - local: "."
        container: /src
    working_directory: /src
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user

tasks:
  build-cloudformation:
    run:
      container: build-env
      command: cdk synth --no-staging
    description: Builds a copy of the Cloudformation used by CDK

```

This is wonderful in that it works, but the assets file generated by CDK becomes based on /src/src (eg:
```json
{
  "files": {
    "{artifactId}": {
      "source": {
        "path": "/src/src/...package file name here",
        "packaging": "file"
      },
      "destinations": {
         ...
      }
    }
}
```

This normally wouldn't be a problem, but we're now trying to get SAM Local going, which is in turn reading those paths and basically going "yep, /src/src doesn't exist, erroring out"
To this end I'd like to either be able to say "Mount the local "." in a path that matches local checkout (eg, if I clone to /home/priorax/asdf, when I run it, mount "." into /home/priorax/asdf in the container).

Example:
```yaml
  build-env:
    dockerfile: build/Dockerfile
    build_directory: .
    volumes:
      - local: "."
        container: $(pwd)
    working_directory: $(pwd)
```

The other methods I see of getting my use case working:

- Use SAM local in batect 
  - This means having docker inside a docker container, which I always get nervous about, especially since this project is used on both Windows and Linux
- Modify the artifact after creation
  - I would need to do this outside of batect to know the correct pathing, which feels like it deviates from having a central shell script.
- Pass through the current directory as an environment file and symlink in the container
  - This just feels overly messy

If you have any other suggestions on how to get this use case working without waiting for a batect release (or if I missed something on https://batect.dev/config/Containers.html#volumes that gives away how I could do this), I'd love to hear it!
