### ISSUE TITLE
Container not passed as healthy, even though it is reporting healthy.

### ISSUE THREAD

**Issue by diffidentDude** [batect/batect#641]
Hey,

I'm doing a POC on this, trying to setup a container with health_check. Unfortunately, even though the health_check is reporting healthy, if I do a docker inspect it's listed as healthy but batect doesn't continue to the next stage.

This does work fine in docker-compose.

Config looks like this,
```
containers:
  selenium-hub:
    health_check:
      interval: 2s
      retries: 5
      start_period: 3s
      command: /opt/bin/check-grid.sh
    image: 'selenium-hub:3.141.59'
    ports:
      - '4444:4444'

  chrome:
    image: 'selenium-node-chrome:3.141.59'
    volumes:
      - '/dev/shm:/dev/shm'

  appcontainer:
    image: node:12.16.1-alpine
    ports:
      - '3000:3000'
      - '8081:8081'

  test:
    dependencies:
      - selenium-hub
      - chrome
    description: Run unit tests
    run:
      container: appcontainer
      command: npm run unit:test:once
      ports:
        - 8081:8081
```

Console
```
$ ./batect test
Running test...
selenium-hub: container started, waiting for it to become healthy...
chrome: running
appcontainer: waiting for dependency selenium-hub to be ready...
```

Console
```
$ docker inspect  --format='{{json .State.Health.Status}}' 762d2ba771359ae60a138588454498d8c880d1039cd7c9340a80ca83ffd7f7ab
"healthy"
```

Console
```
$ ./batect --version
batect version:    0.58.3
Built:             2020-08-25 09:52:42 +0000
Built from commit: 192906ead49a0219c9e8fcfae97e0a58b8c19603 (commit date: 2020-08-25 19:46:38 +1000)
JVM version:       Amazon.com Inc. OpenJDK 64-Bit Server VM 1.8.0_222
OS version:        Mac OS X 10.15.6 (x86_64)
Docker version:    18.3.1-ce (API version: 1.37, minimum supported API version: 1.12, commit: 9ee9f40, operating system: 'linux')
Git version:       2.17.0

For documentation and further information on batect, visit https://github.com/batect/batect.
```
