### ISSUE TITLE
Health check seems to cause timeout issues

### ISSUE THREAD

**Issue by heyheman11** [batect/batect#681]
Hi there, we are using batect to run browser tests against a docz dev server and it seems the health check on the server isn't working and causing timeout issues. 

This is the set-up:

- Node container running a docz dev server
- testcafe image running tests against dev server

**batect**: 0.56

Below is our config file::

```yml
containers:
  testcafe-env:
    image: image/testcafe:1.8.1-alpine-8
    working_directory: /code
    volumes:
      - local: .
        container: /code
        options: cached
    environment:
      IS_CONTAINER: true

  running-site:
    image: image/node:12.19.0-alpine-1
    working_directory: /code
    health_check:
      command: sh -c 'curl -f http://localhost:3000 || exit 1'
      retries: 6
      interval: 10s
    volumes:
      - local: .
        container: /code
        options: cached
    command: npm run start
tasks:
  browser-tests:
    description: Run testcafe tests over docz site
    run:
      container: testcafe-env
      command: npm run test:browser:container
    dependencies:
      - running-site
```

When I run `./batect --ouput=all browser-tests` I get the following output:

```
running-site  | Compiling...
running-site  | [success] [webpackbar] Docz: Compiled successfully in 22.09s (repeated 1 times)
running-site  | [success] [webpackbar] Docz: Compiled successfully in 5.19s
running-site  | Compiled successfully!
browser-tests ! Error: An unexpected exception occurred during execution.
              ! During execution of step of kind 'WaitForContainerToBecomeHealthyStep': java.net.SocketTimeoutException: timeout
browser-tests | Cleaning up...
running-site  | Container stopped.
browser-tests ! The task browser-tests failed. See above for details.
```

I can see that the dev server is healthy through docker ps:

```
docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                   PORTS               NAMES
ba0abe6a5927        /node:12.19.0-alpine-1   "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)                       running-site-ysklff
docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                   PORTS               NAMES
ba0abe6a5927        image/node:12.19.0-alpine-1   "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes (healthy)                       running-site-ysklff
```

Any idea on why it is hanging ?
