### ISSUE TITLE
Advice on caching Docker images in CI that are used by Batect

### ISSUE THREAD

**Issue by binkley** [batect/batect#709]
Looking for advice or Batect documentation update ("Working with CI systems").

```
Run ./batect build-gradle
# Other output deleted
Running build-gradle...
Pulling adoptopenjdk:11-jdk-hotspot...
```

I'm looking for advice on caching the Docker image downloads in GitHub actions.  I'd rather not pull down a new image on each run of Batect in CI.

I tried this in my GitHub actions YAML:
```
      - name: Restore Docker caches  # Batect pulls down a Docker build image
        uses: actions/cache@master
        env:
          cache-name: docker-cache
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.docker-cache') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
```
(I committed a local `.docker-cache` file in the project so GitHub would have a unique cache key.)

I did some research, and on Ubuntu and most other Linuxen, `/var/lib/docker` is the cache for images, including on my personal box.  _However_ ... the local perms on my Ubuntu (Kubuntu) box are below.  GitHub uses `tar` to extract caches, so I'd expect this to all "just work".
```
$ ls -ld /var/lib/docker
drwx--x--x 14 root root 4096 Nov  1 12:30 /var/lib/docker
```
and it isn't clear to me that the in-Batect-container location even applies from within the GitHub Docker container.  It's looking like from my build that the redownloaded image (AdoptOpenJDK11) is saved elsewhere (perhaps in the hosting container?)
