### ISSUE TITLE
Can't create Selenium Grid sessions using Batect

### ISSUE THREAD

**Issue by csxero** [batect/batect#847]
## Background

Creating new sessions using `http://localhost:4444/wd/hub/session` works when we setup our grid using docker compose but doesn't work when we use batect

Any reason why this would happen?

### Error
This is the error we get back using batect when trying to create a new session
```
{
    "value": {
        "message": "Could not start a new session. Could not start a new session. Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: crashed.\n  (chrome not reachable)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'chrome_1.pickles', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.104-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'chrome_1.pickles', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.104-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'selenium-hub.pickles', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.104-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown\nBuild info: version: '4.0.0-beta-3', revision: 'fcfbc6ba25'\nSystem info: host: 'selenium-hub.pickles', ip: '172.19.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.104-microsoft-standard', java.version: '1.8.0_282'\nDriver info: driver.version: unknown"
    }
}
```

## Docker compose file

```
version: "3"
services:
  chrome_1.pickles:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub.pickles
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub.pickles
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
  selenium-hub.pickles:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210402
    container_name: selenium-hub.pickles
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

## Batect file

We use batect for running our ci process. 
```
---
containers:
  automation-setup:
    image: mcr.microsoft.com/playwright:v1.10.0-bionic
    working_directory: /code
    enable_init_process: true
  chrome_1.pickles:
    image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    dependencies:
      - selenium-hub.pickles
    environment:
      SE_EVENT_BUS_HOST: selenium-hub.pickles
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    ports:
      - "6901:5900"
  selenium-hub.pickles:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210402
    health_check:
      command: curl -fsS selenium-hub.pickles:4444/status
      interval: 5s
      retries: 20
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

tasks:
  test-grid:
    description: Run tests over grid
    dependencies:
      - chrome_1.pickles
      - selenium-hub.pickles
    run:
      container: automation-setup
      command: sleep 4m

```

## What we've tried?

- Thought the issue might be related to batect running selenium as root as described here https://stackoverflow.com/a/50642913. But don't think it is now
- Logs looks identical for node and hub.. 😕

At the end of the day we can use docker-compose in the meantime but it would be great to understand why this isn't working 🤔
