### ISSUE TITLE
config-var usage

### ISSUE THREAD

**Issue by erMaurone** [batect/batect#848]
Hi Charles,

Great work on batect - I'm really enjoying it!

Quick question: is there a way I can pass a variable to the docker CMD?

I thought I could use the --config-var, but after trying it looks like it's meant to achieve another goal.
Here's my example.  In pseudo-code i have this in batect.yml:

```yaml
tests-e2e:
  description: Run e2e tests
  container: e2e-tests
  command: /app/run-e2e-tests-in "$env"
```

Then I would run:
`./batect --config-var env=int tests-e2e`

Also, tried to define the variable with 'config_variables' in batect.yaml to no avail.
I prefer not to use env variables as you never know if those are set for other purposes, in which case the env is then left modified after the run.

Is there a way to do this?

Mauro

**Comment by charleskorn** [comment]
Hey @erMaurone, glad to hear it :)

Config variables aren't automatically turned into environment variables, which is why the `$env` there won't be working. There are two possible ways to achieve what you're after:

1. Use config variables and use them to set environment variables for the container, for example:

    ```yaml
    tests-e2e:
      description: Run e2e tests
      container: e2e-tests
      command: /app/run-e2e-tests-in "$env"
      environment:
        env: <{env}
   ```

    (you'll also need to define the `env` config variable in `config_variables`)

    The `<{env}` syntax is a reference to the config variable `env`, which then sets the `env` environment variable for the container. You could then run this with `./batect --config-var env=int tests-e2e`

    If it makes it clearer what is going on, this is an equivalent configuration that uses different names for the config variable and environment variable, which could then be run with `./batect --config-var env_config_variable=int tests-e2e`:

    ```yaml
    tests-e2e:
      description: Run e2e tests
      container: e2e-tests
      command: /app/run-e2e-tests-in "$env_environment_variable"
      environment:
        env_environment_variable: <{env_config_variable}
   ```

2. Don't use config variables and instead pass additional arguments to `./batect`, for example `./batect tests-e2e -- int`. Any arguments after the `--` are appended to the `command` on the task, so the task configuration would look something like this:

    ```yaml
    tests-e2e:
      description: Run e2e tests
      container: e2e-tests
      command: /app/run-e2e-tests-in
   ```
