### ISSUE TITLE
Environment variable substitution doesn't work with default variables

### ISSUE THREAD

**Issue by chinwobble** [batect/batect#872]
This is a great tool that thoughtworkers have introduced me to make docker development easier.

However i encountered a problem with variable substitution.

In bash I can do:
```
echo ${AZURE_CONFIG_DIR:-$HOME/.azure}


```
if the variable `$AZURE_CONFIG_DIR` doesn't exist, it will expand to something like `/home/myuser/.azure`

However when i try to use the following batect config it doesn't work.

```
containers:
  build-env:
    build_directory: ./.devcontainer
    dockerfile: Dockerfile
    working_directory: /app
    run_as_current_user:
      enabled: true
      home_directory: /containeruser/vscode
    build_args:
      TERRAFORM_VERSION: 0.14.6
      TFLINT_VERSION: 0.22.0
      INSTALL_AZURE_CLI: true
      INSTALL_DOCKER: false
      INSTALL_NODE: false
    volumes:
      - local: .
        container: /app
        options: cached
        # should be ${AZURE_CONFIG_DIR:-$HOME/.azure}
        # but the $HOME expansion doesn't work
      - local: ${AZURE_CONFIG_DIR:-$HOME/.azure}
        container: /home/containeruser/.azure
        options: cached
```

Instead what happens is that a folder with the literal name `$HOME` is created in my repo.

The folder structure looks like this:
```
/my-repo/
  /$HOME/
    .azure/
```

Is it possible to get the variable expansion working like bash so that it resolves correctly to `/home/my-user/.azure` ?
