### ISSUE TITLE
Batect fails to remove temporary directory.

### ISSUE THREAD

**Issue by ZhuYeXero** [batect/batect#924]
Hi, 

I want to check the remote git commit in my task, then I mount the local `~/.ssh` in the container.

```
containers:
  runtime-env:
    image: bitnami/git
    volumes:
      - local: .
        container: /app
      - local: ~/.ssh
        container: /home/container-user/.ssh
      - local: <{batect.project_directory}
        container: /code
    working_directory: /code
    run_as_current_user:
      enabled: true
      home_directory: /home/container-user
```

But it occasionally raises the following errors while the task is finished.

```
Error: Could not delete temporary directory '/tmp/batect-home-3526676190332469942'.
java.nio.file.FileSystemException: /tmp/batect-home-3526676190332469942/.ssh: Operation not permitted

Cleaning up: removing 1 temporary directory...

Clean up has failed, and Batect cannot guarantee that all temporary resources created have been completely cleaned up.
You may need to run some or all of the following commands to clean up any remaining resources:
docker rm --force --volumes c3f07830c1598a1d6f7c24506c27620ef29ff524a3d18b2f5cb51cfdffe294aa
rm /tmp/batect-passwd-5284109270127123342
rm /tmp/batect-group-12104143330467655664
rm -rf /tmp/batect-home-3526676190332469942
docker network rm fe1933a55e45b0767c74464eef2ad39c6083171888a682e974f76fc9c5e7dea8
```
Actually, batect cleans all other things except the temporary home dir, and the home dir is already empty when I check it. It seems like the `.ssh` is still mounted when batect wants to remove this temporary home dir, then it fails with above message.
Something interesting is this couldn't turn to a right status once it runs into such situation, but it will be ok when I clone a fresh repo.

Could you please check whether there is a solution can fix this? Thanks.
