### ISSUE TITLE
Getting Batect running on a kubernetes-based Gitlab runner

### ISSUE THREAD

**Issue by Tzrlk** [batect/batect#943]
Given the following gitlab-runner config:
```toml
[[runners]]
  [runners.kubernetes]
  namespace = "gitlab"
  image = "alpine:3.14.0"
  privileged = true
  [[runners.kubernetes.volumes.empty_dir]]
  name = "docker-certs"
  mount_path = "/certs/client"
  medium = "Memory"
```
and the following Gitlab CI config:
```yaml
---

stages:
  - init
  - lint
  - test
  - docs
  - package
  - publish

cache:
  paths:
    - /var/cache/apk/
    - .batect/caches/
    - .build/
    - module/.terraform/

services:
  - docker:19.03.13-dind

variables:

  TERRAFORM_MODULE_DIR:     ${CI_PROJECT_DIR}/module
  TERRAFORM_MODULE_NAME:    k8s-fluxcd
  TERRAFORM_MODULE_SYSTEM:  kubernetes
  TERRAFORM_MODULE_VERSION: ${CI_COMMIT_TAG}

  DOCKER_HOST:        tcp://localhost:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_TLS_VERIFY:  1
  DOCKER_CERT_PATH:   /certs/client
  DOCKER_BUILDKIT:    1

  BATECT_CACHE_TYPE: directory
  BATECT_OPTIONS: >
    --docker-cert-path=${DOCKER_CERT_PATH}
    --no-update-notification
    --skip-prerequisites
    --log-file=batect-debug.log

before_script:
  - >
    apk add
    bash
    curl
    docker
    openjdk11-jre
  - >
    docker login ${DOCKER_REGISTRY}
    --username ${DOCKER_USER}
    --password ${DOCKER_PASS}

init-golang:
  stage: init
  script:
    - env | grep DOCKER | sort
    - ./batect ${BATECT_OPTIONS} golang:deps
  artifacts:
    expire_in: 1 day
    when:      always
    paths:
      - batect-debug.log

...
```
and the following (partial) batect config:
```yaml
containers:

  workspace:
    build_directory: workspace
    build_args:
      TERRAFORM_VERSION:           0.14.8
      TERRAFORM_DOCS_VERSION:      0.10.1
      FLUX_VERSION:                0.13.4
      YQ_VERSION:                  4.9.1
      ASCIIDOCTOR_VERSION:         2.0.12
      ASCIIDOCTOR_DIAGRAM_VERSION: 2.1.0
      GO_DELVE_VERSION:            1.6.0
    run_as_current_user:
      enabled:        true
      home_directory: /home/worker
    volumes:
      - { local: .,               container: /work }
      - { local: ~/.aws,          container: /home/worker/.aws }
      - { type: cache, name: tmp, container: /tmp }
      - { type: cache, name: tfp, container: /home/worker/.terraform.d/plugins }
    environment:
      AWS_PROFILE:           ${AWS_PROFILE:-}
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN:     ${AWS_SESSION_TOKEN:-}
      TF_INPUT:              ${TF_INPUT:-}
      TF_LOG:                ${TF_LOG:-INFO}
      TF_LOG_PATH:           ${TF_LOG_PATH:-./terraform.log}
      TF_IN_AUTOMATION:      ${TF_IN_AUTOMATION:-false}
      VAULT_ADDR:            ${VAULT_ADDR:-}
      VAULT_USER:            ${VAULT_USER:-}
      VAULT_PASS:            ${VAULT_PASS:-}
      GITLAB_TOKEN:          ${GITLAB_TOKEN:-}
tasks:

   ...

  golang:deps:
    description: Initialise dependencies.
    run:
      container: workspace
      command:   go mod download

...
```
the following error is encountered when running a build:
```
$ docker login <redacted> --username ${DOCKER_USER} --password ${DOCKER_PASS}
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
$ env | grep DOCKER | sort
DOCKER_BUILDKIT=1
DOCKER_CERT_PATH=/certs/client
DOCKER_HOST=tcp://localhost:2376
DOCKER_PASS=[MASKED]
DOCKER_REGISTRY=<redacted>
DOCKER_TLS_CERTDIR=/certs
DOCKER_TLS_VERIFY=1
DOCKER_USER=<redacted>
FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR=false
FF_SKIP_DOCKER_MACHINE_PROVISION_ON_CREATION_FAILURE=false
$ ./batect ${BATECT_OPTIONS} golang:deps
Downloading Batect version 0.70.0 from https://updates.batect.dev/v1/files/0.70.0/batect-0.70.0.jar...
#=#=#                                                                         
##O=#  #                                                                      
######################################################################## 100.0%-#O#- #   #                                                                   
##################################                                        47.9%
######################################################################## 100.0%
Running golang:deps...
Building workspace...
Built workspace.
Running go mod download in workspace...
Error: Could not run container workspace.
Starting container '23d16fbbf44bd809f0faebcf614a04fa1822fec0d838f000e5ec0c0171eb73d1' failed: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/batect-passwd-18436127065934139457\\\" to rootfs \\\"/var/lib/docker/overlay2/aafce94c11da26afabfc2b894e591bcced21a86f1a2558882f0fe9e98e90517c/merged\\\" at \\\"/var/lib/docker/overlay2/aafce94c11da26afabfc2b894e591bcced21a86f1a2558882f0fe9e98e90517c/merged/etc/passwd\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
If I remove the `run_as_current_user` configuration, I end up with a different permissions error:
```
go: creating work dir: mkdir /tmp/go-build130985802: permission denied
```

**Comment by charleskorn** [comment]
Thanks for the detailed issue report @Tzrlk.

> ```
> Starting container '23d16fbbf44bd809f0faebcf614a04fa1822fec0d838f000e5ec0c0171eb73d1' failed: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/batect-passwd-18436127065934139457\\\" to rootfs \\\"/var/lib/docker/overlay2/aafce94c11da26afabfc2b894e591bcced21a86f1a2558882f0fe9e98e90517c/merged\\\" at \\\"/var/lib/docker/overlay2/aafce94c11da26afabfc2b894e591bcced21a86f1a2558882f0fe9e98e90517c/merged/etc/passwd\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> ```

The first issue (where `run_as_current_user` is enabled) is caused by the fact that Batect needs to create some temporary files to mount into the container when run as current user is enabled (see [the docs](https://batect.dev/docs/concepts/run-as-current-user-mode/#changes-made-when-running-in-run-as-current-user-mode) for more details). Batect creates these in `/tmp`, and it looks like the Docker daemon you're starting as a service doesn't share the same `/tmp`, so the daemon can't mount these files in.

The good news is that I'm planning to remove this mounting of files for run as current user mode (mounting files like this is also the root cause of #924), so that _should_ fix this issue. Given this is causing pain for two different scenarios for two different people, I'll prioritise this to fix as soon as possible.

> ```
>go: creating work dir: mkdir /tmp/go-build130985802: permission denied
> ```

Are you able to share more surrounding context for this error message? (eg. does it come after `Running go mod download in workspace...` in the output?)

**Comment by charleskorn** [comment]
I've just made a change to how 'run as current user' mode works to not use mounted directories, and will release this shortly. Please give the new version (0.72.0) a go and let me know if it fixes the issue for you.

**Comment by Tzrlk** [comment]
Indeed, that appears to have fixed the issue.

Just for future reference, the key parts for getting the gitlab runners working are:
```toml
[[runners]]
  [runners.kubernetes]
  ...
  privileged = true
  [[runners.kubernetes.volumes.empty_dir]]
  name = "docker-certs"
  mount_path = "/certs/client"
  medium = "Memory"
```
and
```yaml
...
services:
  - docker:19.03.13-dind
variables:
  ...
  DOCKER_HOST:        tcp://localhost:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_TLS_VERIFY:  1
  DOCKER_CERT_PATH:   /certs/client
  ...
before_script:
  - >
    apk add # As long as these are all available in the runner image, it's fine.
    bash
    curl
    docker
    openjdk11-jre
  - >
    docker login ${DOCKER_REGISTRY}
    --username ${DOCKER_USER}
    --password ${DOCKER_PASS}
```
and
```yaml
containers:
  workspace:
    ...
    run_as_current_user:
      enabled: true
      ...
```
with whatever other bits and pieces needed to get tools running smoothly.
