### ISSUE TITLE
Dynamically computed environment variables

### ISSUE THREAD

**Issue by charleskorn** [batect/batect#950]
_Originally posted by @davified in https://github.com/batect/batect/issues/549#issuecomment-893042871_

Hi @charleskorn , thanks for the great work on batect!

I have a question related to this issue. If I should open a new issue instead, please let me know.

Our scenario:
- While some of our env vars are static values, some are dynamic (see GIT_BRANCH, GIT_COMMIT and USERNAME)

```
my-task:
    build_directory: .
    build_target: dev
    volumes:
      - local: .
        container: /app
    working_directory: /app
    environment:
      GIT_BRANCH: ${CI_GIT_BRANCH:-<computed git branch>}
      GIT_COMMIT: ${CI_GIT_COMMIT:-<computed git commit>}
      USERNAME: $(echo ${USER} | sed 's/[\.\_]//g') # USER without punctuations
      <<: *common-static-vars
```

May I know if there's a way to define these dynamic config vars so that it's computed at the time of running the batect tasks?

Thank you!

**Comment by charleskorn** [comment]
Hi @davified, at the moment, there isn't any way built into Batect to do this. There are two options I can think of for this:

* create a shell script for your task that computes the values for you and then invokes the command that needs these values
* if you'd like these environment variables to be available for a range of tasks that use the same container, you could create an entrypoint script that computes the values and then invokes the command, which you could then bake into your image

Do either of these work for your situation? In both cases, the computation of the values would happen inside the container rather than on the host, which is what you appear to be asking for.

**Comment by davified** [comment]
Thanks so much for your prompt response @charleskorn !

In our case, I think we need to compute those variables on the host, outside of Docker, because it has a dependency on (i) `git` and (ii) value of $USER on the host:

```sh
export GIT_BRANCH="${CI_GIT_BRANCH:-$(git branch --show-current)}"
export GIT_SHA="${CI_GIT_COMMIT:-$(git rev-parse --short HEAD)}"
export USERNAME=$(echo ${USER} | sed 's/[\.\_]//g') # USER without punctuations # e.g. david-tan becomes davidtan
```

What you think of this workaround?
1. Create a `./batect-wrapper.sh`, which will compute these variables (GIT_BRANCH, GIT_SHA, USERNAME) on the host
2. Create/update a `batect.local.yml` file with those values
3. Execute the corresponding task

So, users will invoke `./batect-wrapper my-task`, and steps (1) and (2) will run, before (3) (`./batect my-task`) is eventually invoked.

**Comment by charleskorn** [comment]
As a general technique, that will work, however, I think in your particular case you might be able to get away with doing everything in the container. 

For the Git information, given you're mounting the project directory into the container, you should be able to use `git` inside the container to get the information you're after from an entrypoint script - you would need to install `git` in the container's image though.

For the username, you could pass the `USER` environment variable through to the container with something like this...

```yaml
my-task:
    # ... other config for my-task
    environment:
      USER: $USER

```

...and use `sed` in an entrypoint script to remove the punctuation.

**Comment by davified** [comment]
Thanks @charleskorn ! That worked much better than my suggestion :-) 

Just to close the loop on this, this was my implementation of your suggestion:

```
# batect.yml
containers:
  dev:
    build_directory: .  # uses the dockerfile below
   
tasks:
  start-dev:  # use case 1: consuming GIT_BRANCH, GIT_SHA and USER in interactive bash shell
    container: dev
    # ... other config for my-task
    environment:
      USER: $USER

  integration-test:  # use case 2: consuming GIT_BRANCH, GIT_SHA and USER in integration tests
    container: dev
    # ... other config for my-task
    environment:
      USER: $USER

```

## For use case 1:

```
# Dockerfile
FROM somewhere/something:latest

RUN ...

ENTRYPOINT ["/app/bin/start-dev.sh"]
```

```
# bin/start-dev.sh

source bin/init_vars.sh

bash
```

## For use case 2:

```
# bin/integration-test.sh

source bin/init_vars.sh

# run integration test ... (which consumes GIT_BRANCH, GIT_SHA, USERNAME)
```


## Common

```
# bin/init_vars.sh
export GIT_BRANCH="${CI_GIT_BRANCH:-$(git branch --show-current)}"
export GIT_SHA="${CI_GIT_COMMIT:-$(git rev-parse --short HEAD)}"
export USERNAME=$(echo ${USER} | sed 's/[\.\_]//g') # USER without punctuations # e.g. david-tan becomes davidtan
```
